version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      -  POSTGRES_USER=root
      -  POSTGRES_PASSWORD=mokopass
      -  POSTGRES_DB=imple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mokopass@postgres14:5432/simple_bank?sslmode=disable